In [60]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [61]:
df=pd.read_csv('./Data_Set/Churn_Modelling.csv')
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [62]:
print(df.shape)

(10000, 14)

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [64]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [65]:
df.duplicated().sum()

np.int64(0)

In [66]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [67]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [68]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [69]:
#df.drop(['CustomerId','Surname','RowNumber'],axis=1)
df.drop(columns=['CustomerId','Surname','RowNumber'],inplace=True)

In [70]:
df

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [71]:
df=pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)

In [72]:
df

      CreditScore  Age  Tenure  ...  Geography_Germany  Geography_Spain  Gender_Male
0             619   42       2  ...              False            False        False
1             608   41       1  ...              False             True        False
2             502   42       8  ...              False            False        False
3             699   39       1  ...              False            False        False
4             850   43       2  ...              False             True        False
...           ...  ...     ...  ...                ...              ...          ...
9995          771   39       5  ...              False            False         True
9996          516   35      10  ...              False            False         True
9997          709   36       7  ...              False            False        False
9998          772   42       3  ...               True            False         True
9999          792   28       4  ...              False            False        False

[10000 rows x 12 columns]

In [73]:
df

      CreditScore  Age  Tenure  ...  Geography_Germany  Geography_Spain  Gender_Male
0             619   42       2  ...              False            False        False
1             608   41       1  ...              False             True        False
2             502   42       8  ...              False            False        False
3             699   39       1  ...              False            False        False
4             850   43       2  ...              False             True        False
...           ...  ...     ...  ...                ...              ...          ...
9995          771   39       5  ...              False            False         True
9996          516   35      10  ...              False            False         True
9997          709   36       7  ...              False            False        False
9998          772   42       3  ...               True            False         True
9999          792   28       4  ...              False            False        False

[10000 rows x 12 columns]

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CreditScore        10000 non-null  int64
 1   Age                10000 non-null  int64
 2   Tenure             10000 non-null  int64
 3   Balance            10000 non-null  float64
 4   NumOfProducts      10000 non-null  int64
 5   HasCrCard          10000 non-null  int64
 6   IsActiveMember     10000 non-null  int64
 7   EstimatedSalary    10000 non-null  float64
 8   Exited             10000 non-null  int64
 9   Geography_Germany  10000 non-null  bool
 10  Geography_Spain    10000 non-null  bool
 11  Gender_Male        10000 non-null  bool
dtypes: bool(3), float64(2), int64(7)
memory usage: 732.5 KB

In [75]:
X=df.drop(columns=['Exited'])
y=df['Exited']

In [76]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [77]:
len(X)

10000

In [78]:
len(y)

10000

In [79]:
len(X_train)

8000

In [80]:
len(y_train)

8000

In [81]:
X_train.shape

(8000, 11)

In [82]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [83]:
X_train_Scaled=scaler.fit_transform(X_train)
X_test_Scaled=scaler.fit_transform(X_test)

In [84]:
X_test_Scaled.shape

(2000, 11)

In [85]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [86]:
model=Sequential()

In [87]:
model.add(Dense(11,activation='relu', input_dim=11))
model.add(Dense(11,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

c:\Users\R.C\.conda\envs\Deep_Learning\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [88]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_20 (Dense)                │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_22 (Dense)                │ (None, 1)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

In [101]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [102]:
model.fit(X_train_Scaled,y_train,epochs=10,validation_split=0.2)

Epoch 1/10

200/200 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8597 - loss: 0.3461 - val_accuracy: 0.8512 - val_loss: 0.3495
Epoch 2/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8577 - loss: 0.3494 - val_accuracy: 0.8531 - val_loss: 0.3489
Epoch 3/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8537 - loss: 0.3540 - val_accuracy: 0.8525 - val_loss: 0.3476
Epoch 4/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8542 - loss: 0.3491 - val_accuracy: 0.8500 - val_loss: 0.3494
Epoch 5/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8583 - loss: 0.3573 - val_accuracy: 0.8550 - val_loss: 0.3462
Epoch 6/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8577 - loss: 0.3483 - val_accuracy: 0.8519 - val_loss: 0.3476
Epoch 7/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8566 - loss: 0.3465 - val_accuracy: 0.8531 - val_loss: 0.3470
Epoch 8/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8573 - loss: 0.3474 - val_accuracy: 0.8512 - val_loss: 0.3464
Epoch 9/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8655 - loss: 0.3356 - val_accuracy: 0.8519 - val_loss: 0.3467
Epoch 10/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8664 - loss: 0.3317 - val_accuracy: 0.8531 - val_loss: 0.3451

In [103]:
model.layers[0].get_weights()

[array([[-0.11745787,  0.08032288, -0.09332038,  0.24514365, -0.116576  ,
         -0.01483382,  0.02318824,  0.30553105,  0.11133853,  0.17873228,
          0.3399348 ],
        [ 0.47400278,  0.3241724 ,  0.18589434, -0.10961267, -0.8146484 ,
         -0.18657252, -0.2341431 , -0.6283113 , -0.50454676,  0.686175  ,
          1.0247228 ],
        [-0.3991827 ,  0.23847823,  0.382049  , -0.39306158, -0.34120098,
         -0.11995639,  0.12949397,  0.04903303, -0.23777087, -0.17991605,
          0.27419996],
        [-0.6090449 , -0.26079643, -0.09439065,  0.49286905,  0.33975837,
         -0.53399307, -0.5857237 ,  0.39352491, -0.44653565,  0.35277346,
          0.3400916 ],
        [-0.6378599 , -1.0035131 , -0.29573715, -0.5186198 , -0.3208093 ,
          0.8467128 , -0.17400597, -0.12609994, -0.03851485,  1.151845  ,
         -0.23116784],
        [-0.33407092,  0.10197359,  0.03621259,  0.15475129, -0.05339334,
         -0.0940788 ,  0.56635696, -0.25540897,  0.07263538,  0.10862912,
         -0.21209475],
        [ 0.05227022, -0.52927524,  0.7857468 ,  0.23235416, -0.16611136,
         -0.0346187 ,  0.27141073, -0.25932837, -0.03217905,  0.20052028,
          0.51025474],
        [-0.37905365,  0.3577798 , -0.04413518,  0.20807919, -0.2935736 ,
         -0.10067303,  0.4236526 ,  0.23564108, -0.23144056,  0.14264975,
          0.04350522],
        [ 0.15046443,  0.09452327, -0.34727588,  0.49400118,  0.2531062 ,
          0.43266505, -0.15251756, -0.12537391, -0.66515315,  0.00755134,
         -0.12574027],
        [-0.04025596, -0.05485624,  0.11901629, -0.71641093,  0.15555432,
          0.00410472, -0.32695386, -0.17368527, -0.01412719, -0.13760716,
          0.25494304],
        [-0.00295819,  0.07911409,  0.17904164, -0.29557785, -0.3164717 ,
          0.04647987, -0.03153339,  0.35768574,  0.246086  , -0.15100077,
          0.2308898 ]], dtype=float32),
 array([ 0.10231285,  0.16173795,  0.3418599 ,  0.44748807,  0.32867092,
         0.31100237,  0.51423097,  0.5517472 ,  0.32398683, -0.02228134,
        -0.05681298], dtype=float32)]

In [104]:
model.layers[2].get_weights()

[array([[ 0.70788234],
        [-0.65007776],
        [-0.4303902 ],
        [ 0.5490056 ],
        [-0.495802  ],
        [ 0.843812  ],
        [ 0.20229052],
        [-0.605848  ],
        [ 0.44410446],
        [ 0.9548768 ],
        [ 0.7513135 ]], dtype=float32),
 array([-0.22844975], dtype=float32)]

In [105]:
y_log=model.predict(X_test_Scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [106]:
y_pred=np.where(y_log>0.5,1,0)

In [107]:
from sklearn.metrics import accuracy_score

In [108]:
accuracy_score(y_test,y_pred)

0.8595